apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dhruv-tiwari
  annotations:
    github.com/project-slug: dhruv9115/dhruv-tiwari
spec:
  type: other
  lifecycle: unknown
  owner: dhruv
